-- https://html-color-codes.info/colors-from-image/
-- http://i.imgur.com/nj9T2aO.png
local colorgrid = require("colorgrid")
colorgrid:init(7, 7)

colorgrid:addColor(colorgrid:convertHexToColor("#4D1F4D"))
colorgrid:addColor(colorgrid:convertHexToColor("#A63A82"))
colorgrid:addColor(colorgrid:convertHexToColor("#A64B4B"))
colorgrid:addColor(colorgrid:convertHexToColor("#15788C"))
colorgrid:addColor(colorgrid:convertHexToColor("#266EFF"))
colorgrid:addColor(colorgrid:convertHexToColor("#283B73"))
colorgrid:addColor(colorgrid:convertHexToColor("#341F34"))

colorgrid:addColor(colorgrid:convertHexToColor("#FFBCA6"))
colorgrid:addColor(colorgrid:convertHexToColor("#FF5983"))
colorgrid:addColor(colorgrid:convertHexToColor("#F37C55"))
colorgrid:addColor(colorgrid:convertHexToColor("#14CC80"))
colorgrid:addColor(colorgrid:convertHexToColor("#00D5FF"))
colorgrid:addColor(colorgrid:convertHexToColor("#8CB2FF"))
colorgrid:addColor(colorgrid:convertHexToColor("#642DB3"))

colorgrid:addColor(colorgrid:convertHexToColor("#FFFFFF"))
colorgrid:addColor(colorgrid:convertHexToColor("#FFEECC"))
colorgrid:addColor(colorgrid:convertHexToColor("#FFC34D"))
colorgrid:addColor(colorgrid:convertHexToColor("#CBE545"))
colorgrid:addColor(colorgrid:convertHexToColor("#80FFEA"))
colorgrid:addColor(colorgrid:convertHexToColor("#DAEAF2"))
colorgrid:addColor(colorgrid:convertHexToColor("#6F66CC"))

colorgrid:addColor({ 1, 1, 1 })
colorgrid:addColor({ 0.8, 0.8, 0.8 })
colorgrid:addColor({ 0.6, 0.6, 0.6 })
colorgrid:addColor({ 0.4, 0.4, 0.4 })
colorgrid:addColor({ 0.2, 0.2, 0.2 })
colorgrid:addColor({ 0, 0, 0 })
